DROP TABLE IF EXISTS students;
CREATE TABLE students(
id INTEGER PRIMARY KEY AUTOINCREMENT,
fullname VARCHAR(100) NOT NULL,
groups_id REFERENCES groups(id)
);

DROP TABLE IF EXISTS groups;
CREATE TABLE groups(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(100) UNIQUE NOT NULL
);

DROP TABLE IF EXISTS teachers;
CREATE TABLE teachers(
id INTEGER PRIMARY KEY AUTOINCREMENT,
fullname VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS disciplines;
CREATE TABLE disciplines(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name VARCHAR(100) UNIQUE NOT NULL,
teachers_id REFERENCES teachers(id)
);

DROP TABLE IF EXISTS grades;
CREATE TABLE grades(
id INTEGER PRIMARY KEY AUTOINCREMENT,
grade INTEGER NOT NULL,
date_of DATE NOT NULL,
student_id REFERENCES students(id),
discipline_id REFERENCES disciplines(id)
)